name: ej-risk
channels: [conda-forge]
dependencies:
  - python=3.11
  - geopandas
  - pyogrio
  - pandas
  - numpy
  - matplotlib
  - mapclassify
  - libpysal
  - esda
  - spreg
  - splot
  - folium
  - contextily
  - statsmodels
  - jupyterlab
